import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/providers/react-query";
import { NuqsAdapter } from "nuqs/adapters/next/app";
const leagueSpartan = League_Spartan({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface LayoutProps {
  readonly children: React.ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="pt-br">
      <body className={`${leagueSpartan.className} flex min-h-screen flex-col`}>
        <NuqsAdapter>
          <QueryProvider>
            {children}
            <Toaster
              position="top-right"
              richColors
              closeButton
              theme="light"
            />
          </QueryProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
