import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/providers/react-query";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface LayoutProps {
  readonly children: React.ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="pt-br">
      <body className={`${leagueSpartan.className} `}>
        <QueryProvider>
          {children}
          <Toaster position="top-right" richColors closeButton theme="light" />
        </QueryProvider>
      </body>
    </html>
  );
}
